baseURL = 'https://pavlatka.cz/'
languageCode = 'en-us'
title = 'Tomas Moya Pavlatka'
theme = 'bilberry-hugo-theme/v4'

[lsitemap]

[services]
  [services.disqus]
    shortname = 'tomaspavlatka'

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'lovelace'
    tabWidth = 2
    wrapperClass = 'highlight'

[Params]
copyrightBy = "Tomas Moya Pavlatka"
  subtitle = "The journey of mastering new skills starts by tackling today's challenges head-on."
  description = "The journey into the head and mind of software engineer"
  keywords = "software engineer, neovim, java, typescript"
  homeTitle = "Tomas Moya Pavlatka" 
  mainSections = ["post","posts"]
  logo = "img/tomas_pavlatka_profile.jpeg" # Expecting square dimensions
  customImage = "img/tomas_pavlatka_profile.jpeg" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  stickyNav = true
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  # Enable / Disable algolia search
  algolia_search    = true
  algolia_appId     = "WFXNT2GLID"
  algolia_apiKey    = "4fd874a7c7795a13442fa6a20b21f354"
  algolia_indexName = "tomas_pavlatka_articles"

  showSocialMedia = true
  socialMediaLinks = [
    { link = "https://www.linkedin.com/in/tomas-moya-pavlatka/", icon = "fab fa-linkedin", rel = "me" },
    { link = "https://github.com/tomaspavlatka", icon = "fab fa-github" },
  ]

[Params.author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Tomas Moya Pavlatka"
  email = "tomas@pavlatka.cz"
  github = "tomaspavlatka"
  linkedin = "tomas-moya-pavlatka"
