baseURL = 'https://tomaspavlatka.github.io/'
languageCode = 'en-us'
title = 'Tomas Moya Pavlatka'
theme = 'beautifulhugo'

[sitemap]

[services]
  [services.disqus]
    shortname = 'tomaspavlatka'

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'lovelace'
    tabWidth = 2
    wrapperClass = 'highlight'

[Params]
  subtitle = "The journey of mastering new skills starts by tackling today's challenges head-on."
  homeTitle = "Tomas Moya Pavlatka" 
  mainSections = ["post","posts"]
  logo = "img/tomas_pavlatka_profile.jpeg" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true

[Params.author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Tomas Moya Pavlatka"
  email = "tomas@pavlatka.cz"
  github = "tomaspavlatka"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "pages/about/"
    weight = 2

[[menu.main]]
    name = "CV"
    url = "pages/cv/"
    weight = 3

[[menu.main]]
    name = "Certificates"
    url = "pages/certificates/"
    weight = 4

[[menu.main]]
    name = "Daily motivations"
    url = "daily-motivations/"
    weight = 5

[[menu.main]]
    name = "Let's connect"
    url = "pages/lets-connect/"
    weight = 6
